services:
  database:
    container_name: postgres
    image: "postgres:15.2"
    ports:
      - "15432:5432"
    environment:
      - "POSTGRES_DB=${DB_NAME}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"

  app:
    container_name: acme
    build: ./
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    restart: on-failure
    depends_on:
      - database
