services:
  database:
    container_name: mongo
    image: "mongo:7.0.2"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: arqsoft
      MONGO_INITDB_ROOT_PASSWORD: arqsoft2023
      MONGO_INITDB_DATABASE: acmeDB

  mongo-express:
    image: "mongo-express"
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: arqsoft
      ME_CONFIG_MONGODB_ADMINPASSWORD: arqsoft2023
      ME_CONFIG_MONGODB_URL: mongodb://arqsoft:arqsoft2023@mongo:27017/acmeDB?authSource=admin

  app:
    container_name: acme
    build: ./
    ports:
      - "8080:8080"
    environment:
      - DATASOURCE_URL=mongodb://arqsoft:arqsoft2023@mongo:27017/acmeDB?authSource=admin
      - APPLICATION_PROFILE=mongo,bootstrap
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    depends_on:
      - database
