services:
  database:
    container_name: postgres
    image: "postgres:15.2"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=acmeDB"
      - "POSTGRES_USER=arqsoft"
      - "POSTGRES_PASSWORD=arqsoft2023"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@mail.com
      PGADMIN_DEFAULT_PASSWORD: password

  app:
    container_name: acme
    build: ./
    ports:
      - "8080:8080"
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/acmeDB
      - DATASOURCE_USER=arqsoft
      - DATASOURCE_PASSWORD=arqsoft2023
      - DATASOURCE_DRIVER=org.postgresql.Driver
      - DATASOURCE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - APPLICATION_PROFILE=sql,bootstrap
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    depends_on:
      - database
