parameters:
  - name: repo
    type: string

  - name: branch
    type: string

  - name: env
    type: string

  - name: minReplicas
    type: number
    default: 1

  - name: maxReplicas
    type: number
    default: 2

  - name: targetPort
    type: number
    default: 8080

stages:
  - stage:
    displayName: Deploy ${{ parameters.repo }}
    jobs:
      - job:
        timeoutInMinutes: 30
        displayName: Deploy
        steps:
          - checkout: none

          - task: AzureCLI@2
            displayName: Deploy to Container App
            inputs:
              azureSubscription: "Azure for Students(7fc8b461-2e15-4b2d-9926-639d470468c7)"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az config set extension.use_dynamic_install=yes_without_prompt

                az containerapp create \
                  --name ${{ lower(parameters.repo) }}-${{ parameters.env }} \
                  --resource-group acme-rg-${{ parameters.env }} \
                  --environment acme-app-${{ parameters.env }}-env \
                  --image docker.io/1191244/${{ lower(parameters.repo) }}:${{ parameters.env }} \
                  --target-port ${{ parameters.targetPort }} \
                  --ingress 'external' \
                  --query properties.configuration.ingress.fqdn \
                  --min-replicas ${{ parameters.minReplicas }} --max-replicas ${{ parameters.maxReplicas }} \
