trigger:
  - master

pool:
  name: "Azure Pipelines"
  vmImage: ubuntu-latest

steps:
  - task: GoTool@0
    inputs:
      version: "1.21"
    displayName: "Install Go"

  - script: |
      cd infrastructure/cicd && go get dagger.io/dagger@latest
    displayName: "Install Dagger Go SDK and related"

  - script: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sh; cd -; }
    displayName: "Install Dagger CLI"

  - script: make cicd #dagger run go run ci/main.go
    displayName: "Run Dagger"
    env:
      ENVIRONMENT: $(ENVIRONMENT)
      REGISTRY_URL: $(REGISTRY_URL)
      REGISTRY_USERNAME: $(REGISTRY_USERNAME)
      REGISTRY_TOKEN: $(REGISTRY_TOKEN)
