trigger:
  - master

pool:
  name: "Azure Pipelines"
  vmImage: ubuntu-latest

variables:
  - group: dagger-environment-variables

steps:
  - task: GoTool@0
    inputs:
      version: "1.21.0"
    displayName: "Install Go"

  - script: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sh; cd -; }
    displayName: "Install Dagger CLI"

  - script: make cicd
    displayName: "Run Dagger"
    env:
      ENVIRONMENT: $(ENVIRONMENT)
      REGISTRY_URL: $(REGISTRY_URL)
      REGISTRY_USERNAME: $(REGISTRY_USERNAME)
      REGISTRY_TOKEN: $(REGISTRY_TOKEN)
